plugins {
    id 'java'
    id 'checkstyle'
    id 'application'
    id 'jacoco'
    id 'gg.jte.gradle' version '3.2.1'
    id 'org.springframework.boot' version '3.3.5'
    id 'io.spring.dependency-management' version '1.1.7'
}

group = 'ru.mentee.power'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

ext {
    servletVersion = '6.1.0'
    jteVersion = '3.2.1'
    tomcatVersion = '11.0.18'
    springBootVersion = '3.3.5'
}

dependencies {

    compileOnly "jakarta.servlet:jakarta.servlet-api:${servletVersion}"
    implementation "gg.jte:jte:${jteVersion}"
    implementation "gg.jte:jte-runtime:${jteVersion}"
    implementation 'gg.jte:jte-spring-boot-starter-3:3.2.1'
    implementation 'org.springframework.boot:spring-boot-starter-web'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testRuntimeOnly 'org.junit.platform:junit-platform-launcher:1.10.2'
    testImplementation 'org.assertj:assertj-core:3.27.7'
    testImplementation 'org.mockito:mockito-core:5.14.2'
    testImplementation 'org.mockito:mockito-junit-jupiter:5.14.2'
}

application {
    mainClass = 'ru.mentee.power.crm.spring.Application'
}

springBoot {
    mainClass = 'ru.mentee.power.crm.spring.Application'
}

bootRun {
    mainClass = 'ru.mentee.power.crm.Application'
}

jte {
    sourceDirectory = project.file("src/main/jte").toPath()
    contentType = "Html"
    binaryStaticContent = false
}

task copyJteTemplates(type: Copy) {
    description = 'Копирует JTE шаблоны из jte в resources для Spring'
    from 'src/main/jte'
    into 'src/main/resources/jte'
    include '**/*.jte'
}


checkstyle {
    toolVersion = '10.12.4'
    maxErrors = 0
    maxWarnings = 999
    configFile = file("${rootDir}/config/checkstyle/checkstyle.xml")
}

tasks.withType(Checkstyle).configureEach {
    exclude 'ru.mentee.power.progress'
}

jacoco {
    toolVersion = '0.8.14'
}

test {
    useJUnitPlatform()
    finalizedBy jacocoTestReport
}

jacocoTestReport {
    dependsOn test
    reports {
        xml.required = false
        csv.required = false
        html.required = true
        html.outputLocation = layout.buildDirectory.dir('reports/jacoco/test/html')
    }
}

jacocoTestCoverageVerification {
    dependsOn jacocoTestReport
    violationRules {
        rule {
            excludes = [
                    'ru.mentee.power.devtools.progress'
            ]
            limit {
                minimum = 0.35
            }
        }
    }
}

tasks.named("checkstyleMain") {
    group = "verification"
}

tasks.named("checkstyleTest") {
    group = "verification"
}

check {
    dependsOn jacocoTestCoverageVerification
}
